repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^data-processing-pipeline/
      - id: end-of-file-fixer
        files: ^data-processing-pipeline/
      - id: check-yaml
        files: ^data-processing-pipeline/
      - id: check-added-large-files
        files: ^data-processing-pipeline/
      - id: check-merge-conflict
        files: ^data-processing-pipeline/

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^data-processing-pipeline/
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        files: ^data-processing-pipeline/
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: ^data-processing-pipeline/pipeline/
        exclude: ^data-processing-pipeline/tests/
        args: [--config-file=data-processing-pipeline/pyproject.toml]
